// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDym2Es0CEISdVq_9TvYPEkvIwLihj0CBA',
    appId: '1:892167164706:web:5831918798f715ba200b7b',
    messagingSenderId: '892167164706',
    projectId: 'call-me-d0afb',
    authDomain: 'call-me-d0afb.firebaseapp.com',
    storageBucket: 'call-me-d0afb.appspot.com',
    measurementId: 'G-0ELKJ9C80V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUMgHPy0dR4YNaWRhwzbVZAwTdPqws9fI',
    appId: '1:892167164706:android:ebc77f773b14e34c200b7b',
    messagingSenderId: '892167164706',
    projectId: 'call-me-d0afb',
    storageBucket: 'call-me-d0afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcQOBd0jmJr0-09vlcPIXaWLXlu_s1AE',
    appId: '1:892167164706:ios:2fc19c3343fc5683200b7b',
    messagingSenderId: '892167164706',
    projectId: 'call-me-d0afb',
    storageBucket: 'call-me-d0afb.appspot.com',
    iosBundleId: 'com.example.callMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgcQOBd0jmJr0-09vlcPIXaWLXlu_s1AE',
    appId: '1:892167164706:ios:2fc19c3343fc5683200b7b',
    messagingSenderId: '892167164706',
    projectId: 'call-me-d0afb',
    storageBucket: 'call-me-d0afb.appspot.com',
    iosBundleId: 'com.example.callMe',
  );
}
